#ifndef __FOCUS_PAD_H__
#define __FOCUS_PAD_H__

typedef enum  {
  MODE_POWER=0,
  MODE_SPEED,
  MODE_CONSISTENCY,
  MODE_NONE
}  PAD_MODE;  


 typedef enum   {
  PAD_STATE_WAITING_TO_CALIBRATE,
  PAD_STATE_CALIBRATE,
  PAD_STATE_MODE_SELECT,
  PAD_STATE_ACTIVE,
  PAD_STATE_LOGGING,
  PAD_STATE_DONE_LOGGING 
} PAD_STATE;


#endif
